### ISSUE TITLE
Missing Code

### ISSUE THREAD

**Issue by strikermed** [somany-io/robot#1]
I'm attempting this robot project: https://www.instructables.com/So-Many-Robots-DIY-Print-in-Place-Robot-for-STEM-L/

I went to grab the code for the project, and found that the code is missing and there is only an apache licensing agreement.  Was this meant to be available?

**Comment by somanyrobots-io** [comment]
https://www.instructables.com/So-Many-Robots-DIY-Print-in-Place-Robot-for-STEM-L/

`Step 5: Flash Robot Explorer Firmware`

Can download the file  [Robot Explorer.uf2](https://github.com/somany-io/robot/raw/refs/heads/main/Robot%20Explorer.uf2) to flash the firmware. The uf2 file contains Python files and related dependencies.

Source code can be loaded by editing in Thonny, see https://projects.raspberrypi.org/en/projects/getting-started-with-the-pico/0 for additional info on getting started.
